name: Frontend CD Pipeline

on:
  workflow_run:
    workflows: ["Frontend CI Pipeline"]
    types:
      - completed

jobs:
  deploy:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: self-hosted   

    steps:
      - name: Deploy new containers
        run: |
          bash /home/ubuntu/deployment/deploy.sh
      